### PR TITLE
docs: remove unused region tags

### PR DESCRIPTION
**Pull request by Strykrol**
Finalizes work started in #325. These tags have proliferated on Devsite; old tags are safe to remove.

### CODE REVIEW

**Comment by Strykrol** [comment]
This should be a trivial PR as the new correct region tags are now used in docs. Please merge, thank you for helping with this and related PRs!

**Review by lesv — APPROVED** [review]

**Comment by Strykrol** [comment]
Status here?

**Comment by lesv** [comment]
It's failing on windows. I'll merge if you are ok with this / can't merge, we typically review and let you merge.

**Comment by lesv** [comment]
# Windows
```
Warning:  bootstrap class path not set in conjunction with -source 1.7
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
  symbol:   variable SecurityMarksName
  location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest
[INFO] 1 error


[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project google-cloud-securitycenter: Compilation failure
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
Error:    symbol:   variable SecurityMarksName
Error:    location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest


Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
  symbol:   variable SecurityMarksName
  location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest
[INFO] 1 error

Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project google-cloud-securitycenter: Compilation failure
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
Error:    symbol:   variable SecurityMarksName
Error:    location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :google-cloud-securitycenter

Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
  symbol:   variable SecurityMarksName
  location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest


Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project google-cloud-securitycenter: Compilation failure
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
Error:    symbol:   variable SecurityMarksName
Error:    location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest
Error:  -> [Help 1]


Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
  symbol:   variable SecurityMarksName
  location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest


Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project google-cloud-securitycenter: Compilation failure
Error:  /D:/a/java-securitycenter/java-securitycenter/google-cloud-securitycenter/src/test/java/com/google/cloud/securitycenter/v1beta1/SecurityCenterClientTest.java:[1411,17] cannot find symbol
Error:    symbol:   variable SecurityMarksName
Error:    location: class com.google.cloud.securitycenter.v1beta1.SecurityCenterClientTest
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :google-cloud-securitycenter
Error: Process completed with exit code 1.
```

**Comment by lesv** [comment]
@hannah-tsai PTAL

**Comment by Strykrol** [comment]
@lesv - I don't know why the windows failure would have anything to do with the changes made, to be frank :/   I also do not have write access to this repository, so I was hoping someone could merge it once it's safe. Thanks for responding, let me know if there's anything further I can do here.

**Comment by lesv** [comment]
@Strykrol Np - If you just ask to merge on approval in the comments, I usually do it and would have ping'd earlier.  Hopefully @hannah-tsai or someone on her team will take a look on Tuesday - most likely it's something that used to be included is required to be added to the `pom.xml` files - I'll try rebuilding again - incase it's just something that didn't get read from Maven.  If it's not fixed by Wednesday of next week, ping me, and I'll see what we can do.

**Comment by Strykrol** [comment]
Oh okay, I can do that moving forward - thank you! We'll check back next week.

**Comment by Strykrol** [comment]
@lesv bumping 👍

**Review by lesv — APPROVED** [review]

**Comment by Strykrol** [comment]
Thank you!!

**Pull request merged**
